# Generated by Django 4.2.16 on 2025-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='hero_backgrounds/'),
        ),
    ]
