# Generated by Django 4.2.16 on 2025-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0004_video_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MZ Tailors', max_length=100)),
                ('logo_image', models.ImageField(upload_to='logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
