# Generated by Django 4.2.16 on 2025-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_customers', models.IntegerField(default=2500, help_text='Number of happy customers')),
                ('years_experience', models.IntegerField(default=25, help_text='Years of experience')),
                ('expert_tailors', models.IntegerField(default=50, help_text='Number of expert tailors')),
                ('satisfaction_rate', models.IntegerField(default=99, help_text='Satisfaction rate percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
